- lombok.config
- src/main/java/uk/gov/hmcts/reform/demo/errorhandling/GlobalExceptionHandler.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/errorhandling/ExceptionResponseTest.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/errorhandling/GlobalExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/errorhandling/exceptions/AccountNotFoundExceptionTest.java
https://tools.hmcts.net/jira/browse/PUB-503
Added Tests for Exception Handling
```
[ ] Yes
[x] No
```
> PUB-503 - Exception Handling Tests

- src/test/java/uk/gov/hmcts/reform/rsecheck/config/SwaggerConfigurationTest.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
added swagger config test
```
[ ] Yes
[ ] No
```
> added swagger config test

- build.gradle
- config/owasp/suppressions.xml
- src/main/resources/application.yaml
N/A
Updated version of log4j to 2.15.0 following vulnerability in library
See https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot for details.
```
[ ] Yes
[x] No
```
> Updated version of log4j to 2.15

- charts/pip-account-management/Chart.yaml
https://hmcts-reform.slack.com/archives/C02ECRF7T1R/p1644501458036309
Upgrade Charts versions before AKS cluster upgrade.
```
[ ] Yes
[ X ] No
```
> Update Chart version for AKS Upgrade

- README.md
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/NotFoundException.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/UserNotFoundException.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/CustomExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1051
Added api for getting a user by provenance and provenance id that will return instance of PiUser or return a 404 if the user is not found
```
[ ] Yes
[x] No
```
> PUB-1051 added user retrieval for provenanceId

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PUB-1175
Added Hikari to ensure that the jdbc connection uses connection pooling.
```
[ ] Yes
[x] No
```
> PUB-1175 - Added hikari to application.yaml

- build.gradle
- charts/pip-account-management/values.yaml
- config/owasp/suppressions.xml
N/A
Fixed issue with gradle in demo and added in extension app ID.
```
[ ] Yes
[x] No
```
> Updated build gradle and fixed dependency issue

- config/owasp/suppressions.xml
added owasp suppression
```
[ ] Yes
[x] No
```
> added owasp supporession for spring plugin

- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.dev.template.yaml
- charts/pip-account-management/values.yaml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PUB-961
Updated config for new B2C
```
[ ] Yes
[x] No
```
> PUB-961 - Updated config for B2C

- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.yaml
- config/owasp/suppressions.xml
PUB-961
Add env to secret values names
```
[ ] Yes
[ x ] No
```
> PUB-961 Add env to secret values names

- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.yaml
- src/main/resources/application.yaml
N/A
Fix environment issue
```
[ ] Yes
[x] No
```
> Added env variable for identity issuer

- build.gradle
n/a bug
added exclusion for sonarcloud
```
[x] Yes
[ ] No
```
> added exclusion

- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.yaml
N/A
Added missing secret
```
[ ] Yes
[x] No
```
> Added missing secret into values.yaml

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
Fix the functional tests
[ ] Yes
[x] No
> Fix functional tests

- README.md
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
Merge master into develop
[] Yes
[x] No
> Update master branch

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/config/PersistenceConfiguration.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/PiUser.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/errored/ErroredPiUser.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1187
Add creation date to account user table
```
[ ] Yes
[x] No
```
> PUB-1187 Add creation date to account user table

- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.dev.template.yaml
N/A
Updated to latest chart
```
[ ] Yes
[x] No
```
> Updated Chart

- charts/pip-account-management/values.dev.template.yaml
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/ListType.java
https://tools.hmcts.net/jira/browse/PUB-1246
Updated List Types for COP list
```
[ ] Yes
[x] No
```
> Pub 1246 COP Schema

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SensitivityTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/MediaApplicationService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1478
Changed logs to remove the email and replace with the user ID
```
[ ] Yes
[x] No
```
> PUB-1478 Mask logs

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1318
Added new endpoint to update the last verified date for a given provenance user id.
Note: This is branched off the other media verification flow changes
```
[ ] Yes
[x] No
```
> PUB 1318 Media verification link up

- src/main/java/uk/gov/hmcts/reform/pip/account/management/config/WebClientConfig.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/config/WebClientCreationTest.java
https://tools.hmcts.net/jira/browse/PUB-1521
Changing how client registrations are read in to fix servletRequest cannot be null error.
```
[ ] Yes
[x] No
```
> PUB-1521 Service-to-service fix

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PUB-1476
Updated app insight name to have PIP as prefix.
```
[ ] Yes
[x] No
```
> PUB-1476 Updated app insight name

- src/main/resources/application.yaml
N/A
Updated the Cron timer to run once per day
```
[ ] Yes
[x] No
```
> Updated cron timer

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/MediaApplicationService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/MediaApplicationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SchedulerTest.java
https://tools.hmcts.net/jira/browse/PUB-1569
- Updated cron job for media application reporting to run every Monday at 12am
- Updated logic so the media application reporting email request is only sent if its not empty
```
[ ] Yes
[x] No
```
> PUB-1569 Updated cron job and logic

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/PiUser.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/helpers/DateTimeHelper.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/helpers/DateTimeHelperTest.java
https://tools.hmcts.net/jira/browse/PUB-1568
Updated to use UTC rather than BST
```
[ ] Yes
[x] No
```
> PUB-1568 - Updated Date Time

- README.md
- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.dev.template.yaml
- charts/pip-account-management/values.yaml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PUB-1589
Updated flyway so that it can run locally
```
[ ] Yes
[ ] No
```
> PUB-1589 - Updated flyway

- infrastructure/main.tf
- infrastructure/providers.tf
- infrastructure/tf-db-main.tf
- infrastructure/tf-db-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-1595
Create infrastructure code for new account
```
[ ] Yes
[x] No
```
> PUB-1595 - Updated infrastructure

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/PiUser.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/Roles.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/UserProvenances.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AzureUserService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AzureUserServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1613
- Added new endpoint to get all users except third party and filter by all attributes of a user
- Added delete endpoint of a user
- Added update endpoint to update a users role
```
[ ] Yes
[x] No
```
> PUB-1613 System Admin User management dashboard

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1611
Added endpoints for:
- Retrieving Third Party users
- Getting a user by their ID
```
[ ] Yes
[x] No
```
> PUB-1611 - 3rd party

- build.gradle
Upgrade postgresql dependency to fix CVE-2022-41946
```
[ ] Yes
[x] No
```
> CVE-2022-41946 Upgrade postgresql dependency 

- infrastructure/tf-db-main.tf
- src/main/resources/db/migration/V1.5__add-created-date-to-mv.sql
https://tools.hmcts.net/jira/browse/PUB-1745
Re-creates the PI User MV with the created date field
```
[ ] Yes
[x] No
```
> PUB-1745 - Recreate MV

- infrastructure/tf-db-main.tf
https://tools.hmcts.net/jira/browse/PUB-1745
Re-add role.
```
[ ] Yes
[x] No
```
> PUB-1745 - Re-add role

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/helpers/EmailHelper.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/Roles.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/helper/EmailHelperTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1057
Added new endpoint to get an admin user (excluding system admin) by their email and provenance
```
[ ] Yes
[x] No
```
> PUB-1057 Admin management

- .github/workflows/ci.yml
- Dockerfile
- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- config/pmd/ruleset.xml
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/config/AzureBlobConfigurationTestConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/config/AzureConfigurationClientTestConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/config/SwaggerPublisherTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/GetWelcomeTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SensitivityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/ViewTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/SystemAdminAccountException.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/SensitivityService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/config/AzureBlobConfigurationTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/config/AzureConfigurationClientTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/config/WebClientTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SubscriptionServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1678
Upgraded account management from Java 11 to 17.
```
[ ] Yes
[x] No
```
> PUB-1678 Java 17 upgrade

- .github/workflows/ci.yml
- Dockerfile
- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- config/pmd/ruleset.xml
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/config/AzureBlobConfigurationTestConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/config/AzureConfigurationClientTestConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/config/SwaggerPublisherTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/GetWelcomeTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SensitivityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/ViewTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/AzureAccount.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/errored/ErroredAzureAccount.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/SensitivityService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/SystemAdminAccountService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/config/AzureBlobConfigurationTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/config/AzureConfigurationClientTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/config/WebClientTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SubscriptionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SystemAdminAccountServiceTest.java
N/A
PR to merge Freeze to Master
```
[ ] Yes
[x] No
```
> Merge Freeze to Master

- config/owasp/suppressions.xml
N/A
Added suppression as already on latest version + part of spring
```
[ ] Yes
[x] No
```
> Added suppression

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/MediaApplicationDto.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/validation/annotations/ValueOfEnum.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/validation/validator/ValueOfEnumValidator.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/validation/validator/ValueOfEnumValidatorTest.java
https://tools.hmcts.net/jira/browse/PUB-1288
Added validation to the create media application.
```
[ ] Yes
[x] No
```
> PUB-1288 Create media application validation

- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
https://tools.hmcts.net/jira/browse/PUB-1733
We cannot improve the response time of the api call. Reason is that Api is taking sometime to establish a connection with Azure Graph Api. Once first request has been entertained, rest of the api request only couple of milliseconds to process.
Method to create Azure account has been refactored.
[ ] Yes
[x] No
> PUB-1733 Azure account creation refactoring

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationTest.java
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/PUB-1774
Added functional tests for GetImageById endpoint
```
[ ] Yes
[x] No
```
> PUB-1774 functional test for GetImageById

- build.gradle
Fix Owasp Dependency to latest 8.0.2
[ ] Yes
[x] No
> Fix Owasp Dependency to latest

- build.gradle
- config/owasp/suppressions.xml
N/A
Updated suppressions
```
[ ] Yes
[x] No
```
> Updated suppressions

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-1910
Updated dependencies
```
[ ] Yes
[x] No
```
> PUB-1910 - Updated dependencies

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/UserWithProvenanceNotFoundException.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/CustomExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1828
Log info when finding user by provenance ID
```
[ ] Yes
[x] No
```
> PUB-1828 Log info when finding user by provenance ID

- build.gradle
- config/owasp/suppressions.xml
Upgrade springboot version for CVE-2023-28708
```
[ ] Yes
[x] No
```
> Upgrade springboot version for CVE-2023-28708

- README.md
https://tools.hmcts.net/jira/browse/PUB-1991
Updated to retrigger build
```
[ ] Yes
[x] No
```
> PUB-1991 - Update to trigger rebuild

- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/InactiveAccountManagementService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/MediaApplicationService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/MediaApplicationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SystemAdminAccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1732
Update logging
```
[ ] Yes
[x] No
```
> PUB-1732 Update logging

- build.gradle
- charts/pip-account-management/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-1996
Updated dependencies
```
[ ] Yes
[x] No
```
> PUB-1996 - Updated dependencies

- config/owasp/suppressions.xml
Suppress CVE-2023-34411
https://nvd.nist.gov/vuln/detail/CVE-2023-34411
```
[ ] Yes
[x] No
```
> Suppress CVE-2023-34411

- build.gradle
- config/owasp/suppressions.xml
Update microsoft-graph dependency to fix CVE-2023-2976. Suppress CVE-2023-34462
```
[ ] Yes
[x] No
```
> Fix CVE-2023-2976 and suppress CVE-2023-34462

- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/WebConfiguration.java
Ignore trailing slash in spring boot v3 endpoints
```
[ ] Yes
[x] No
```
> Ignore trailing slash in spring boot v3 endpoints

- build.gradle
- config/owasp/suppressions.xml
N/A
Fixed pipeline vulnerability 
```
[ ] Yes
[x] No
```
> Fixed vulnurability

- build.gradle
- config/owasp/suppressions.xml
N/A
Fixed Spring CVE
```
[ ] Yes
[x] No
```
> Fixed spring CVE

- infrastructure/providers.tf
- infrastructure/tf-db-flexible-secrets.tf
- infrastructure/tf-db-flexible.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PUB-2130
Created Azure flexible server for postgres 15, storing creds in KV.
```
[ ] Yes
[x] No
```
> PUB-2130 Create Postgres 15 Azure Flexible Server

- Jenkinsfile_parameterized
- infrastructure/providers.tf
- infrastructure/tf-db-flexible-secrets.tf
- infrastructure/tf-db-flexible.tf
- infrastructure/tf-db-main.tf
Infrastructure to migrate lower environments. Starting with Sandbox + Demo
```
[ ] Yes
[x] No
```
> PUB-2188 - Migrating lower environments

- infrastructure/tf-db-flexible.tf
Migrate lower environments - demo
```
[ ] Yes
[x] No
```
> PUB-2188 - Migrate Lower Environments - Demo

- infrastructure/tf-db-main.tf
Remove role from test env
```
[ ] Yes
[x] No
```
> PUB-2188 - Migrate Lower Environments - Test

- config/owasp/suppressions.xml
Added suppression
```
[ ] Yes
[x] No
```
> PUB-2188 - Added suppression

- build.gradle
- config/owasp/suppressions.xml
- infrastructure/tf-db-main.tf
Removed role from staging
```
[ ] Yes
[x] No
```
> PUB-2188 - Added staging

- charts/pip-account-management/values.stg.template.yaml
- infrastructure/tf-db-flexible.tf
Migrate lower environments
```
[ ] Yes
[x] No
```
> PUB-2188 - Migrate lower environments

- infrastructure/tf-db-main.tf
Migrate ITHC environment
```
[ ] Yes
[x] No
```
> PUB-2188 - Updated ITHC

- infrastructure/tf-db-main.tf
https://tools.hmcts.net/jira/browse/PUB-2189
Removed old role
```
[ ] Yes
[x] No
```
> PUB-2189 - Removed role

- infrastructure/tf-db-flexible.tf
- infrastructure/tf-db-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-2189
Migration Part 2
```
[ ] Yes
[x] No
```
> PUB-2189 - Part 2

- infrastructure/providers.tf
- infrastructure/tf-db-flexible.tf
- infrastructure/tf-db-main.tf
Removed old config
```
[ ] Yes
[x] No
```
> PUB-2222 - Removed old config

- infrastructure/tf-db-flexible-secrets.tf
- infrastructure/tf-db-secrets.tf
Change old values
```
[ ] Yes
[x] No
```
> PUB-2222 - Remove old postgres

- infrastructure/tf-db-main.tf
- infrastructure/tf-db-secrets.tf
> PUB-2222 - Removed old postgres

- infrastructure/tf-db-main.tf
Remove old postgres from ITHC and Staging
```
[ ] Yes
[x] No
```
> PUB-2222 - Removed ITHC + Staging

- infrastructure/tf-db-flexible.tf
Updated permissions trigger
```
[ ] Yes
[x] No
```
> PUB-2222 - Updated permissions

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2153
Add OPA Press List listType
```
[ ] Yes
[ ] No
```
> PUB-2153 Add OPA Press List listType

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/CustomAccountRetrievalTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountFilteringController.java
https://tools.hmcts.net/jira/browse/PUB-1851
Added Java Docs to MI controller to describe the response
```
[ ] Yes
[x] No
```
> PUB-1851 - Added docs to MI controller

- README.md
- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.yaml
https://tools.hmcts.net/jira/browse/PUB-2245
Updated README + removed unused chart value
```
[ ] Yes
[x] No
```
> PUB-2245 - Updated README

- .github/workflows/terraform_format.yml
- infrastructure/providers.tf
- infrastructure/tf-db-flexible.tf
https://tools.hmcts.net/jira/browse/PUB-2182
Add terraform_format.yml
```
[ ] Yes
[X] No
```
> PUB-2182 add terraform_format.yml

- .github/workflows/terraform_format.yml
- README.md
- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.yaml
- infrastructure/providers.tf
- infrastructure/tf-db-flexible.tf
Merge code freeze branch to Master
```
[ ] Yes
[x] No
```
> Merge code freeze branch to Master

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountFilteringController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AzureAccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/BulkAccountCreationController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/InactiveAccountManagementController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminAccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/TestingSupportController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/ViewController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountFilteringService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AzureAccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AzureUserService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/BulkAccountCreationService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/SubscriptionService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/ViewService.java
https://tools.hmcts.net/jira/browse/PUB-2279
Fix sonarqube code smell
```
[ ] Yes
[x] No
```
> PUB-2279 Fix sonarqube code smells

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PUB-2351
Update keep alive timeout
```
[ ] Yes
[x] No
```
> PUB-2351 - Updated keep alive parameter

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2121
Update pip-data-models version
```
[ ] Yes
[x] No
```
> PUB-2121 Update pip-data-models version

- README.md
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/PiUser.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountFilteringServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SensitivityServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2363
Update Data Models version number to add SSO user provenance
```
[ ] Yes
[X] No
```
> PUB-2363 - Add SSO user provenance

- infrastructure/providers.tf
https://tools.hmcts.net/jira/browse/PUB-2046
Update provider version
```
[ ] Yes
[x] No
```
> Fix pipeline - Updated provider

- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminAccountTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminB2CAccountTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminAccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminB2CAccountController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/model/SystemAdminAccount.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/SystemAdminAccountService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/SystemAdminB2CAccountService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminB2CAccountControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SystemAdminAccountServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SystemAdminB2CAccountServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2481
Create system admin account for SSO user
```
[ ] Yes
[x] No
```
> PUB-2481 Create system admin account for SSO user

- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/InactiveAccountManagementService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/InactiveAccountManagementServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1567
Check inactive user for Crime and also delete crime user from CaTH database after 208 days.
[ ] Yes
[x] No
> PUB-1567 Check inactive user for Crime

- charts/pip-account-management/Chart.yaml
- charts/pip-account-management/values.dev.template.yaml
- charts/pip-account-management/values.yaml
N/A
Fixed functional tests
```
[ ] Yes
[x] No
```
> Fixed functional tests

- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SubscriptionServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2581
Remove SpringBootTest annotation from unit tests
```
[ ] Yes
[x] No
```
> PUB-2581 - Remove SpringBootTest annotation from unit tests

- README.md
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/AuditRepositoryTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/MediaApplicationRepositoryTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepositoryTest.java
- src/integrationTest/resources/application-integration-jpa.yaml
- src/main/java/uk/gov/hmcts/reform/pip/account/management/config/AzureBlobConfiguration.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/config/AzureConfigurationClient.java
https://tools.hmcts.net/jira/browse/PUB-2579
Add account-management data repository tests
```
[ ] Yes
[x] No
```
> PUB-2579 Add account-management data repository tests

- charts/pip-account-management/values.stg.template.yaml
https://tools.hmcts.net/jira/browse/PUB-2574
Updated max system admin accounts for Staging pod deployment
```
[ ] Yes
[x] No
```
> Updated max system admin accounts staging

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2712
Add CIC Daily Hearing List
```
[ ] Yes
[x] No
```
> PUB-2712 Add CIC Daily Hearing List

- infrastructure/tf-db-flexible.tf
Add dblink in allowed extensions
[ ] Yes
[x] No
> PUB-2729 Add dblink in allowed extensions

- infrastructure/tf-db-flexible.tf
- src/main/resources/db/migration/V1.7__add_subscription_table.sql
- src/main/resources/db/migration/V1.8__add_mv-sdp-subscription.sql
- src/main/resources/db/migration/V1.9__add_subscription_list_type_table.sql
Check dbserver links and move data from subscription management to account management
[ ] Yes
[x] No
> PUB-2729 Check dbserver links and move data

- infrastructure/tf-db-flexible.tf
remove view from code
[ ] Yes
[x] No
> PUB-2729 remove view from code

- src/main/resources/db/migration/V1.7__add_subscription_table.sql
- src/main/resources/db/migration/V2.0__add_party_name_column_to_subscription.sql
> PUB-2729 check dbserver link

- infrastructure/tf-db-flexible.tf
Give permission to sdp view
[ ] Yes
[x] No
> PUB-229 Give permission to sdp view

- build.gradle
- charts/pip-account-management/values.dev.template.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/FunctionalAccountFilteringControllerTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/CustomAccountRetrievalTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepositoryTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountFilteringController.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountFilteringService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountFilteringControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountFilteringServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2708
Added new MI endpoint to return model
```
[ ] Yes
[x] No
```
> PUB-2708 - Added new MI endpoint

- infrastructure/tf-db-flexible.tf
- src/main/resources/db/migration/V1.7__add_subscription_table.sql
- src/main/resources/db/migration/V1.8__add_mv-sdp-subscription.sql
- src/main/resources/db/migration/V1.9__add_subscription_list_type_table.sql
- src/main/resources/db/migration/V2.0__add_party_name_column_to_subscription.sql
Add dbserver link and scripts to create table
[ ] Yes
[x] No
> PUB-2729 Add dbserver link and scripts to create table

- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepositoryTest.java
https://tools.hmcts.net/jira/browse/PUB-2708
Fixed integration test
```
[ ] Yes
[x] No
```
> PUB-2708 - Fixed integration test

- infrastructure/tf-db-flexible.tf
- src/main/resources/db/migration/V1.7__add_subscription_table.sql
- src/main/resources/db/migration/V1.8__add_mv-sdp-subscription.sql
- src/main/resources/db/migration/V1.9__add_subscription_list_type_table.sql
- src/main/resources/db/migration/V2.0__add_party_name_column_to_subscription.sql
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Pub 2729 check dbserver link

- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/subscription/SubscriptionListTypeTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/subscription/SubscriptionTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/SubscriptionListTypeRepositoryTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/SubscriptionRepositorySearchTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/SubscriptionRepositoryTest.java
- src/integrationTest/resources/application-integration-jpa.yaml
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/subscription/SubscriptionListTypeService.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/subscription/SubscriptionService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/subscription/SubscriptionListTypeServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/subscription/SubscriptionServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2809
Add integration tests for unknown user, alongside validation
```
[ ] Yes
[x] No
```
> PUB-2728 - Added integration tests + Updated validation

- build.gradle
- charts/pip-account-management/Chart.yaml
https://tools.hmcts.net/jira/browse/PUB-2827
Updated helm chart to use new version
```
[ ] Yes
[x] No
```
> PUB-2827 - Updated Helm Chart

- infrastructure/tf-db-flexible.tf
Testing extension removal
Testing extension removal
```
[ ] Yes
[x] No
```
> Testing extension removal

- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/account/AccountTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/account/SystemAdminB2CAccountTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/subscription/SubscriptionTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2920
Updated auth checks for endpoints
```
[ ] Yes
[x] No
```
> PUB-2920 - Updated auth checks for endpoints

- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/subscription/SubscriptionService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/subscription/SubscriptionServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2905
Stop deletion of list types if there are remaining location subscription
```
[ ] Yes
[x] No
```
> PUB-2905 Stop deletion of list types if there are remaining location subscription

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-2959
Updated spring
```
[ ] Yes
[x] No
```
> PUB-2981 - Updated spring + suppressions

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-2960
Add Magistrates Adult Court List
```
[ ] Yes
[x] No
```
> PUB-2960 Add Magistrates Adult Court List

- README.md
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepositoryTest.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/pip/account/management/service/account/InactiveAccountManagementService.java
- src/test/java/uk/gov/hmcts/reform/pip/account/management/service/account/InactiveAccountManagementServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2472
Update account deletion to include past dates
```
[ ] Yes
[x] No
```
> PUB-2472 Update account deletion to include past dates
